### ISSUE TITLE
Permitir que multiplos canais utilizem a API

### ISSUE THREAD

**Issue by rn4n** [micebot/server#28]
Tanto o bot do Discord quanto da Twitch utilizam a API sem especificar qual é o canal que está consultando e persistindo os dados. Isso porque a versão [v0.1.0](https://github.com/micebot/server/milestone/2?closed=1) da API tinha como objetivo realizar um CRUD básico integrado com Twitch e Discord (para o [#desafio333](https://github.com/micebot/desafio333)).

Se a ideia for pra frente, o ideal é fazer com que múltiplos canais possam utilizar a estrutura. Essa issue é para discutir como podemos fazer isso. 😃

**Comment by rn4n** [comment]
O bot do Discord deixa de fazer sentido agora, era somente um requisito pro desafio333.

Talvez o ideal seja começar do zero a implementação de uma plataforma que suporte o uso de múltiplos canais, integrado somente com a Twitch. @milafrn tem interesse?

**Comment by milafrn** [comment]
@rn4n Tenho sim.
